apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: svc-c7
spec:
  cidr: 10.117.0.0/16
  disabled: true
  natOutgoing: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pod-c7
spec:
  cidr: 10.237.0.0/16
  disabled: true
  natOutgoing: false
