apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: svc-c14
spec:
  cidr: 10.124.0.0/16
  disabled: true
  natOutgoing: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: pod-c14
spec:
  cidr: 10.244.0.0/16
  disabled: true
  natOutgoing: false
