apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-c1
spec:
 cidr: 10.111.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-c1
spec:
 cidr: 10.241.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: svc-c2
spec:
 cidr: 10.112.0.0/16
 natOutgoing: false
 disabled: true
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
 name: pod-c2
spec:
 cidr: 10.242.0.0/16
 natOutgoing: false
 disabled: true